"""add_fk_ingestion_jobs_to_documents

Revision ID: 520660ac8f99
Revises: eb2ab0029b85
Create Date: 2026-06-11 12:56:00.620407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520660ac8f99'
down_revision: Union[str, Sequence[str], None] = 'eb2ab0029b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ingestion_jobs_document_id', 'documents', ['document_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ingestion_jobs_document_id', type_='foreignkey')

    # ### end Alembic commands ###
