"""add_agent_runs_and_agent_steps

Revision ID: 546d3d25d351
Revises: e7a5ab96f085
Create Date: 2026-06-11 13:28:47.052966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546d3d25d351'
down_revision: Union[str, Sequence[str], None] = 'e7a5ab96f085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('ticket_id', sa.String(length=36), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='running | waiting_approval | completed | failed | terminated'),
    sa.Column('risk_level', sa.String(length=16), nullable=False, comment='low | medium | high | critical'),
    sa.Column('plan_json', sa.Text(), nullable=True, comment='JSON array of plan steps'),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('budget_json', sa.Text(), nullable=True, comment='JSON: {"max_steps": 10, "max_tool_calls": 20, "max_latency_ms": 120000}'),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('final_action', sa.String(length=64), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('termination_reason', sa.String(length=128), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('total_tool_calls', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('tool_error_count', sa.Integer(), nullable=False),
    sa.Column('permission_deny_count', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=True, comment='JSON array of errors'),
    sa.Column('approvals_json', sa.Text(), nullable=True, comment='JSON array of approval records'),
    sa.Column('audit_trace_json', sa.Text(), nullable=True, comment='JSON array of audit entries'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)

    op.create_table('agent_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=32), nullable=False, comment='plan | execute | observe | evaluate | approve | finalize'),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tool_params_json', sa.Text(), nullable=True),
    sa.Column('tool_result_json', sa.Text(), nullable=True),
    sa.Column('permission_check', sa.String(length=32), nullable=True, comment='allowed | denied | needs_approval'),
    sa.Column('permission_reason', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('recovered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_steps_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_steps_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_steps_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_steps_run_id'))

    op.drop_table('agent_steps')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_session_id'))

    op.drop_table('agent_runs')
    # ### end Alembic commands ###
