"""add_ingestion_jobs_table

Revision ID: da37c67d5d9a
Revises: b0c426dadb0e
Create Date: 2026-06-11 12:18:06.682584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da37c67d5d9a'
down_revision: Union[str, Sequence[str], None] = 'b0c426dadb0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='queued | running | completed | failed'),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='ingest_document | run_eval | process_agent_job'),
    sa.Column('task_params', sa.Text(), nullable=True, comment='JSON-encoded params'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_document_id'))

    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
