"""add_documents_table

Revision ID: eb2ab0029b85
Revises: da37c67d5d9a
Create Date: 2026-06-11 12:35:03.946767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2ab0029b85'
down_revision: Union[str, Sequence[str], None] = 'da37c67d5d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash for dedup'),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft | active | archived | deleted'),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True, comment='Detected language: zh, en, de, etc.'),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('security_level', sa.String(length=20), nullable=False),
    sa.Column('allowed_roles', sa.String(length=512), nullable=True, comment='Comma-separated roles'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))

    op.drop_table('documents')
    # ### end Alembic commands ###
